version: '3'

services:
  web:
    build: 
      dockerfile: ./docker/python/Dockerfile
      context: ./
    container_name: "my-apps"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - '8001:5000'
    volumes:
      - .:/srv
      
